# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Keyword used to render this snippet of content.', max_length=255, unique=True)),
                ('status', models.IntegerField(choices=[(1, b'Published'), (2, b'Draft'), (3, b'Removed')], default=2)),
                ('body', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('url_text', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, upload_to=b'featured')),
                ('notes', models.TextField(blank=True, help_text='Extra notes about this field. Not public.')),
                ('is_featured', models.BooleanField(default=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-is_featured', '-created'),
            },
        ),
    ]
