# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps', '0001_initial'),
        ('organizations', '0001_initial'),
        ('awards', '0001_initial'),
        ('hubs', '0001_initial'),
        ('actionclusters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationaward',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization'),
        ),
        migrations.AddField(
            model_name='hubaward',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.Award'),
        ),
        migrations.AddField(
            model_name='hubaward',
            name='hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubs.Hub'),
        ),
        migrations.AddField(
            model_name='applicationaward',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Application'),
        ),
        migrations.AddField(
            model_name='applicationaward',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.Award'),
        ),
        migrations.AddField(
            model_name='actionclusteraward',
            name='actioncluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actionclusters.ActionCluster'),
        ),
        migrations.AddField(
            model_name='actionclusteraward',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.Award'),
        ),
    ]
