# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import geoposition.fields
import us_ignite.common.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actionclusters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=b'name', unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='event name')),
                ('slug', us_ignite.common.fields.AutoUUIDField(blank=True, editable=False, unique=True)),
                ('status', models.IntegerField(choices=[(1, b'Published'), (2, b'Draft'), (3, b'Removed')], default=1)),
                ('image', models.ImageField(blank=True, help_text=b'Image suggested size: 500x400px', upload_to=b'events')),
                ('description', models.TextField(verbose_name='short description')),
                ('start_datetime', models.DateTimeField(verbose_name='Start Date/Time')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='End Date/Time')),
                ('timezone', models.CharField(choices=[(b'US/Alaska', b'US/Alaska'), (b'US/Aleutian', b'US/Aleutian'), (b'US/Arizona', b'US/Arizona'), (b'US/Central', b'US/Central'), (b'US/East-Indiana', b'US/East-Indiana'), (b'US/Eastern', b'US/Eastern'), (b'US/Hawaii', b'US/Hawaii'), (b'US/Indiana-Starke', b'US/Indiana-Starke'), (b'US/Michigan', b'US/Michigan'), (b'US/Mountain', b'US/Mountain'), (b'US/Pacific', b'US/Pacific'), (b'US/Pacific-New', b'US/Pacific-New'), (b'US/Samoa', b'US/Samoa')], default=b'US/Eastern', max_length=30)),
                ('address', models.TextField()),
                ('scope', models.IntegerField(choices=[(1, b'National'), (2, b'Regional'), (3, b'Global')], default=1)),
                ('audience_other', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True, help_text='Please enter a URL starting with http or https', max_length=500)),
                ('section', models.IntegerField(choices=[(1, 'Default'), (2, 'Global City Teams')], default=1, help_text='Section where this event will be listed. Default is the main section.')),
                ('tickets_url', models.URLField(blank=True, help_text='Please enter a URL starting with http or https', max_length=500, verbose_name='Tickets URL')),
                ('position', geoposition.fields.GeopositionField(blank=True, max_length=42)),
                ('is_ignite', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('actionclusters', models.ManyToManyField(blank=True, to='actionclusters.ActionCluster', verbose_name='communities')),
                ('audiences', models.ManyToManyField(blank=True, to='events.Audience')),
            ],
            options={
                'ordering': ('-is_featured', 'start_datetime'),
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=b'name', unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EventURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(help_text='Please enter a URL starting with http or https', max_length=500, verbose_name='URL')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
