# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 04:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import geoposition.fields
import taggit.managers
import us_ignite.common.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=b'name', unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=b'name', unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('slug', us_ignite.common.fields.AutoUUIDField(blank=True, editable=False, help_text='Slug used for your profile. Recommended FirstName-LastName', unique=True)),
                ('avatar', models.ImageField(blank=True, help_text='Select image to use as avatar. If an image is not provided Gravatar will be used.', max_length=500, upload_to=b'avatar')),
                ('website', models.URLField(blank=True, help_text='Please enter a URL starting with http or https', max_length=500)),
                ('quote', models.TextField(blank=True, help_text='Short quote.', max_length=140)),
                ('bio', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True, help_text='What do you have to contribute? Design skills? Programming languages? Subject matter expertise? Project management experience?')),
                ('availability', models.IntegerField(choices=[(0, 'I do not have any availability at this time'), (1, 'I have limited availability'), (2, 'I might be available'), (3, 'Yes, I would love to join a project')], default=0)),
                ('interests_other', models.CharField(blank=True, max_length=255)),
                ('category_other', models.CharField(blank=True, max_length=255)),
                ('position', geoposition.fields.GeopositionField(blank=True, max_length=42)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False, help_text=b'By marking the profile as public it will be shown in search results.')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Category', verbose_name='I associate most with')),
                ('interests', models.ManyToManyField(blank=True, to='profiles.Interest')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(help_text='Please enter a URL starting with http or https', max_length=500, verbose_name='URL')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
    ]
