# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 04:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, b'Published'), (2, b'Draft'), (3, b'Removed')], default=2)),
                ('wp_id', models.CharField(blank=True, editable=False, max_length=255)),
                ('wp_type', models.CharField(blank=True, editable=False, max_length=255)),
                ('wp_url', models.URLField(blank=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('section', models.IntegerField(choices=[(1, 'Default'), (2, 'Global City Teams')], default=1, help_text='Section where this event will be listed. Default is the main section.')),
                ('content', models.TextField(blank=True)),
                ('content_html', models.TextField(blank=True, editable=False)),
                ('excerpt', models.TextField(blank=True)),
                ('excerpt_html', models.TextField(blank=True, editable=False)),
                ('publication_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('update_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_custom', models.BooleanField(default=False, help_text='If marked will stop the importer from updating the content of this Post.')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('-is_featured', '-publication_date'),
                'get_latest_by': 'publication_date',
            },
        ),
        migrations.CreateModel(
            name='PostAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_id', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('attachment', models.FileField(blank=True, upload_to=b'posts')),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('caption', models.TextField(blank=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
